import streamlit as st
import pandas as pd
import plotly.express as px
from data_manager import initialize_session_state, get_kpis
from styles import apply_custom_css

# 1. Page Configuration
st.set_page_config(page_title="VendorFlow AI", page_icon="📊", layout="wide")
apply_custom_css()
initialize_session_state()

# 2. Sidebar Navigation
st.sidebar.title("🛠️ VendorFlow AI")
st.sidebar.markdown("---")
menu = st.sidebar.radio("Main Menu", ["Dashboard Home", "Onboarded Vendors", "Approached Leads"])
st.sidebar.markdown("---")

# 3. View Logic
if menu == "Dashboard Home":
    st.title("📈 Vendor Pipeline Overview")
    
    # --- KPI SECTION ---
    metrics = get_kpis()
    conv_rate = (metrics['active_vendors'] / max(metrics['total_approached'], 1)) * 100
    
    st.markdown(f"""
    <div style="display: flex; gap: 20px; margin-bottom: 30px;">
        <div style="flex: 1; background-color: white; padding: 20px; border-radius: 10px; border: 1px solid #E5E7EB; box-shadow: 0 2px 4px rgba(0,0,0,0.05);">
            <p style="margin: 0; color: #6B7280; font-size: 14px; font-weight: 600;">📦 TOTAL ONBOARDED</p>
            <h2 style="margin: 5px 0 0 0; color: #111827;">{metrics['total_onboarded']}</h2>
        </div>
        <div style="flex: 1; background-color: white; padding: 20px; border-radius: 10px; border: 1px solid #E5E7EB; box-shadow: 0 2px 4px rgba(0,0,0,0.05);">
            <p style="margin: 0; color: #6B7280; font-size: 14px; font-weight: 600;">🎯 LEADS IN PIPELINE</p>
            <h2 style="margin: 5px 0 0 0; color: #111827;">{metrics['total_approached']}</h2>
        </div>
        <div style="flex: 1; background-color: white; padding: 20px; border-radius: 10px; border: 1px solid #E5E7EB; box-shadow: 0 2px 4px rgba(0,0,0,0.05);">
            <p style="margin: 0; color: #6B7280; font-size: 14px; font-weight: 600;">⚡ PIPELINE CONVERSION</p>
            <h2 style="margin: 5px 0 0 0; color: #111827;">{conv_rate:.1f}%</h2>
        </div>
    </div>
    """, unsafe_allow_html=True)

    # --- ACTIONABLE ANALYTICS ---
    col_a, col_b = st.columns(2)

    with col_a:
        st.subheader("👥 Lead Sourcing by Team")
        df_app = st.session_state.approached_df
        
        # Look for the 'first_contacted_by' column generated by data_manager.py
        if not df_app.empty and 'first_contacted_by' in df_app.columns:
            team_data = df_app['first_contacted_by'].dropna().value_counts().reset_index()
            team_data.columns = ['Team Member', 'Leads Generated']
            
            # Filter out random junk data/blank spaces if any exist
            team_data = team_data[team_data['Team Member'].str.len() > 1]
            
            fig_team = px.bar(
                team_data, x='Leads Generated', y='Team Member', orientation='h', 
                color='Leads Generated', color_continuous_scale='Teal',
                title="Who is bringing in the most leads?"
            )
            fig_team.update_layout(yaxis={'categoryorder':'total ascending'}, showlegend=False, margin=dict(l=0, r=0, t=30, b=0))
            st.plotly_chart(fig_team, use_container_width=True)
        else:
            st.info("Team sourcing data (First Contacted By) is currently empty.")

    with col_b:
        st.subheader("🏷️ Top 10 Product Categories")
        
        # Point specifically to the 'category' column in the approached leads
        if not df_app.empty and 'category' in df_app.columns:
            # Capitalize the categories so "beauty" and "Beauty" are grouped together
            df_app['category_clean'] = df_app['category'].astype(str).str.title().str.strip()
            # Remove 'Nan' values that get converted to string
            cat_data = df_app[df_app['category_clean'] != 'Nan']['category_clean'].value_counts().nlargest(10).reset_index()
            cat_data.columns = ['Product Category', 'Count']
            
            fig_cat = px.treemap(
                cat_data, path=['Product Category'], values='Count',
                color_discrete_sequence=px.colors.qualitative.Pastel
            )
            fig_cat.update_layout(margin=dict(l=0, r=0, t=10, b=0))
            st.plotly_chart(fig_cat, use_container_width=True)
        else:
            st.info("Could not locate the 'Category' column.")

elif menu == "Onboarded Vendors":
    st.title("📂 Onboarded Vendor Directory")
    st.dataframe(st.session_state.onboarded_df, use_container_width=True)

elif menu == "Approached Leads":
    st.title("🎯 Approached Leads & Tracking")
    st.dataframe(st.session_state.approached_df, use_container_width=True)
